pipeline {
    agent any

    environment {
        APP_DIR = "messaging_app"
        VENV = ".venv"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/scottandee/alx-backend-python'
            }
        }

        stage("Setup Virtual Environment"){
            steps {
                echo 'Setting up virtual environment...'
                sh '''
                    cd $APP_DIR
                    python3 -m venv $VENV
                    . $VENV/bin/activate
                '''
            }
        }

        stage('Install Dependencies') {
            steps {
                echo 'Installing dependencies...'
                sh '''
                    cd $APP_DIR
                    . $VENV/bin/activate
                    pip install --upgrade pip
                    pip install -r requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    cd $APP_DIR
                    . $VENV/bin/activate
                    pytest --junitxml=pytest-report.xml
                '''
            }
        }

    }

    post {
        always {
            junit "${APP_DIR}/pytest-report.xml"
        }

        success {
            echo "Tests passed successfully"
        }

        failure {
            echo "Tests failed"
        }
    }
}