pipeline {
    agent {
        docker {
            image 'python:3.11-slim'
            args '-u root'
        }
    }

    environment {
        APP_DIR = "messaging_app"
    }

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                    cd $APP_DIR
                    pip install --upgrade pip
                    pip install -r requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    cd $APP_DIR
                    pytest --junitxml=pytest-report.xml
                '''
            }
        }
    }

    post {
        always {
            junit "${APP_DIR}/pytest-report.xml"
        }

        success {
            echo "Tests passed successfully"
        }

        failure {
            echo "Tests failed"
        }
    }
}
